### ISSUE TITLE
小白完全看不懂啊

### ISSUE THREAD

**Issue by redscarful** [pppyyyccc/streamshield-proxy#1]
可不可以出个详细教程

**Comment by pppyyyccc** [comment]
![Uploading photo_2024-07-23_15-23-03.jpg…]()

**Comment by pppyyyccc** [comment]
![photo_2024-07-23_15-23-03](https://github.com/user-attachments/assets/677f84e6-f3e4-4421-8f80-79c88a2be07b)

**Comment by mjj996** [comment]
> 可不可以出个详细教程

额……pixman你看了吗

**Comment by pppyyyccc** [comment]
> 可不可以出个详细教程

![photo_2024-07-23_15-23-03](https://github.com/user-attachments/assets/eb0e0169-2301-4742-8baf-7124b0bd3292)

**Comment by hecarli555** [comment]
看不懂的自行学习docker相关教程
