### ISSUE TITLE
文件无法播放

### ISSUE THREAD

**Issue by NP-Prob** [pppyyyccc/streamshield-proxy#10]
# Bug Report

## 描述
按教程在国外vps上搭建之后，经测试，在potplayer中pixman可以连通，但本项目显示文件无法播放。

## 复现步骤（ip已脱敏处理）
1. 在国外VPS上按照pixman官网的 [Docker 镜像 pixman/pixman 使用说明 贴](https://pixman.io/topics/17) 部署好了 Pixman Docker 镜像，并且在本地potplayer上使用：
```
http://ip:port/4gtv.m3u
http://ip:port/tptv_proxy.m3u
http://ip:port/thetv.m3u
http://ip:port/beesport.m3u
```
可以在播放列表里看到各台的选择。

2. 在同一VPS上运行
`docker pull ppyycc/streamshield-proxy:latest`

3. 新建`docker-compose.yml`文件如下：
```
services:
  streamshield-proxy:
    image: ppyycc/streamshield-proxy:latest
    restart: always
    container_name: streamshield-proxy
    environment:
      - CUSTOM_DOMAIN=http://ip:5000
      - VPS_HOST=http://ip:4994
      - INCLUDE_MYTVSUPER="free"
      - DEBUG="true"
      - CHINAM3U="true"
    ports:
      - 4994:4994
```
`docker compose up -d`后在本地用potplayer打开链接`http://ip:4994`显示文件无法播放。
在edge浏览器打开`http://ip:4994`显示`Fobidden`。

## 预期行为
在Potplayer播放列表可正常显示各台选项

## 环境信息
- VPS操作系统：Debian 12
- 本地操作系统：Windows 10
- 播放使用软件：Potplayer 64位 v. 241216(1.7.22398)
- Docker Version: 27.4.0

## 日志输出
```
Environment variables:
CUSTOM_DOMAIN: http://ip:5000
VPS_HOST: http://ip:4994
SECURITY_TOKEN: undefined
INCLUDE_MYTVSUPER: free
CHINAM3U: true
DEBUG: true
MYTVSUPER configuration: free
MYTVSUPER URL: http://ip:5000/mytvsuper-tivimate.m3u
Configured sources:
- 四季: http://ip:5000/4gtv.m3u
- MytvSuper Free: ./mytvfree.m3u
- TheTV: http://ip:5000/thetv.m3u
- Beesport 直播源: http://ip:5000/beesport.m3u
- 央视频: http://ip:5000/ysp.m3u
- 蜀小果: http://ip:5000/sxg.m3u
- 中国移动 iTV 平台: http://ip:5000/itv_proxy.m3u
- 江苏移动魔百盒 TPTV: http://ip:5000/tptv_proxy.m3u
StreamShield Proxy is listening on port 4994
所有频道的 M3U 播放列表已生成并保存为 'mytvfree.m3u'。
Received request for: //
403 Forbidden: //
Received request for: //
403 Forbidden: //
Received request for: /
403 Forbidden: /
```

## 附加信息
任何其他有助于理解问题的信息。

**Comment by pppyyyccc** [comment]
必须加上一个安全token 不然跑起来马上被白嫖

**Comment by NP-Prob** [comment]
> 必须加上一个安全token 不然跑起来马上被白嫖

主要是我现在跑都跑不起来，不确定是哪里的问题。我开始加了token也跑不起来，所以去掉token跑了一遍然后把日志po上来了。
目前的问题是因为必须要加token导致的吗？
