### ISSUE TITLE
/testtoken/proxy/   可以代理任何网站 会不会导致不安全 是否可以加个白名单 让用户自行添加域名

### ISSUE THREAD

**Issue by hjh-cn** [pppyyyccc/streamshield-proxy#2]
<img width="1100" alt="螢幕截圖 2024-07-27 09 54 46" src="https://github.com/user-attachments/assets/afc82db5-e986-48f1-9d23-5d6d90924b6b">

**Comment by pppyyyccc** [comment]
安全token寫不對代理不了
