### ISSUE TITLE
老大还在更新吗，看30秒就要卡几秒

### ISSUE THREAD

**Issue by vbskycn** [pppyyyccc/streamshield-proxy#4]
老大还在更新吗，看30秒就要卡几秒

vps速度很快本地也OK

甲骨文arm机机  24G

上面搭建的梯子直接连看 4gtv很流畅

想用上代理程序，家人可以直接看，但是看30秒就要卡几秒

老大有时间优化一下吗

**Comment by pppyyyccc** [comment]
1. 播放器增大缓存次数 2. 换香港的vps
