### ISSUE TITLE
新版1.25 MytvSuper 获取不到

### ISSUE THREAD

**Issue by qdkevin2010** [pppyyyccc/streamshield-proxy#5]
新版1.25 在已添加 MytvSuper 付费 token 前提下，变量 “true” 提取不到任何频道，但是 “free” 却可以提取到免费频道，token 在本地 pixman 下部署是正常的。

**Comment by pppyyyccc** [comment]
我没有付费token 不能帮你测试，你可以在tg里找我私聊测试

**Comment by X-Firefly** [comment]
新版只有mytvsuper 不能播放 频道能获取到，但播放显示403 台湾频道正常。

**Comment by pppyyyccc** [comment]
> 新版只有mytvsuper 不能播放 频道能获取到，但播放显示403 台湾频道正常。

代码问题 今明能修
