### ISSUE TITLE
1.26版本4gtv查看ts地址并没有进行代理

### ISSUE THREAD

**Issue by luyiwind** [pppyyyccc/streamshield-proxy#6]
在最新的1.26版本下，查看4GTV ts地址没有添加代理。回退到1.25版本后正常。

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:76837209

#EXTINF:4,
https://litvpc-hichannel.cdn.hinet.net/live/pool/4gtv-4gtv001

**Comment by pppyyyccc** [comment]
1.3.0已解决bug
