### ISSUE TITLE
能否添加屏蔽频道列表的环境变量

### ISSUE THREAD

**Issue by money114** [pppyyyccc/streamshield-proxy#8]
开启变量CHINAM3U="true"后，StreamShield Proxy会将pixman中所有国内频道都进行合并，其中sxg已经失效了，但在频道列表中还是存在，所以希望能添加屏蔽频道列表的环境变量，当频道列表失效后能进行屏蔽

**Comment by kmtycjj-tyx** [comment]
我设置了CHINAM3U="true"但还是看不了国内频道，是什么原因呢？？

**Comment by pppyyyccc** [comment]
国内的可以去看肥羊的docker速度快
