### ISSUE TITLE
速度好像有优化空间

### ISSUE THREAD

**Issue by alexallen1** [pppyyyccc/streamshield-proxy#9]
首先感谢你的项目~
我是香港2G家宽i5 4500跑着debian11，docker跑了pixman o11和你的项目，推流给大陆看
晚上11:30 o11看翡翠台不卡，看streamshield-proxy反代的偶尔卡一下 速率500KB/S勉强临界
fast.com测速有70mbps+

因为连接同一个vps，无其他变量~。

**Comment by pppyyyccc** [comment]
因为两个连接方式不一样 mpd就是协议交互麻烦 你可以在终端加大缓存试试。
另外o11推流可能用的底层协议栈也不一样，晚上香港到大陆对好多协议是qos限流的。 
我用au的机器代理晚上看翡翠基本不算卡。

**Comment by alexallen1** [comment]
> 因为两个连接方式不一样 mpd就是协议交互麻烦 你可以在终端加大缓存试试。 另外o11推流可能用的底层协议栈也不一样，晚上香港到大陆对好多协议是qos限流的。 我用au的机器代理晚上看翡翠基本不算卡。

请教streamshield-proxy怎么加大缓存~

**Comment by pppyyyccc** [comment]
tvbox 或者ok影视里调大缓存 我测试过在docker里做异步缓存没什么意义 主要是vps到终端线路的问题 vps本身到iptv源的宽带是足够的
